### ISSUE TITLE
broken 1.1.2

### ISSUE THREAD

**Issue by exomarty** [yariplus/nodebb-plugin-featured-topics-extended#5] opened 2016-08-29 00:53 UTC
Seems like feature topics button and reorder doesnt work on last node :(

**Comment by yariplus** [comment] 2016-08-29 01:26
This should be fixed already, is the plugin updated to 0.1.6 in the ACP?

**Comment by exomarty** [comment] 2016-08-29 02:57
oh no, its on 0.1.5
nodebb packages didnt pop it yet :(

**Comment by exomarty** [comment] 2016-08-29 02:58
maybe need to put "compatibility": "^1.1.0"
not sure tho

**Comment by yariplus** [comment] 2016-08-29 05:25
Should be fixed now.

**Comment by exomarty** [comment] 2016-09-01 11:46
last updates broke it again :p

**Comment by yariplus** [comment] 2016-09-01 17:05
I know I broke it on 0.1.7, is 0.1.8 broke for you?

**Comment by exomarty** [comment] 2016-09-01 19:32
yes, no results on news page and was making nodebb crash, didnt check error logs i disabled it yesterday

**Comment by yariplus** [comment] 2016-09-01 19:54
Hmm, just tried it on a fresh install and no issues.

What version of nodejs are you running?

**Comment by exomarty** [comment] 2016-09-01 19:54
1.1.2

**Comment by yariplus** [comment] 2016-09-01 20:12
@exomarty 

`node -v`

**Comment by exomarty** [comment] 2016-09-01 22:37
node -v
v4.4.7

**Comment by yariplus** [comment] 2016-09-02 05:58
Hmm, I'm not sure what the problem could be.

**Comment by yariplus** [comment] 2016-09-02 17:58
@exomarty Could you post the crash log when you get a chance?

**Comment by vyprik** [comment] 2016-09-02 18:19
@yariplus I have the same problem on 1.1.0 (redis). Have I create new issue and put my logs or better post here?

**Comment by yariplus** [comment] 2016-09-02 18:24
@vyprik You can post the logs here, thanks.

**Comment by vyprik** [comment] 2016-09-02 20:53
@yariplus 

```
error: TypeError: Cannot read property 'tid' of null
    at Command.callback (/Users/claus/apps/nbb/nbb110/node_modules/nodebb-plugin-featured-topics-extended/lib/plugin.js:115:13)
    at RedisClient.return_reply (/Users/claus/apps/nbb/nbb110/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/Users/claus/apps/nbb/nbb110/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/Users/claus/apps/nbb/nbb110/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/Users/claus/apps/nbb/nbb110/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/Users/claus/apps/nbb/nbb110/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by yariplus** [comment] 2016-09-02 22:35
Thanks, i see what the problem is now.

**Comment by yariplus** [comment] 2016-09-03 05:02
Latest version should fix the crashes.

**Comment by vyprik** [comment] 2016-09-03 08:36
I reinstalled your plugin. No errors now, but empty page.
![image](https://cloud.githubusercontent.com/assets/1611159/18223771/6c2fe834-71ca-11e6-8aa7-09af81d5cf06.png)
Trying different id of categories (with topics) - the same.

**Comment by exomarty** [comment] 2016-09-03 16:15
works perfect for me now 0.1.10

**Comment by yariplus** [comment] 2016-09-03 17:29
@vyprik Are you using the topic tools here to feature the topic?:

![](http://puu.sh/qYDVX/9f2684db51.png)

Marking a category id will only auto-feature new topics.

**Comment by vyprik** [comment] 2016-09-03 18:18
@yariplus oh, sorry! I didn't know about this. Now it's working.
Thanks a lot!

**Comment by yariplus** [comment] 2016-09-03 19:36
Good to hear!

**Closed as completed by yariplus** 2016-09-03 19:36 UTC
